[package]
name = "airnode-rrp-explorer"
version = "0.1.0"
edition = "2018"
authors = ["EnormousCloud"]
license = "MIT"

[dependencies]
yew = { git = "https://github.com/yewstack/yew" }
log = "0.4"
wasm-logger = "0.2"
gloo = "0.3"
serde = "1"
serde_derive = "1"